In [40]:
import pandas as pd
import numpy as np
%matplotlib inline
import matplotlib.pyplot as plt
from sklearn import linear_model

In [41]:
df = pd.read_csv("C:\\Users\\shiva\\Desktop\\MACHINE LEARNING\\canada_per_capita_income.csv")
df.head(10)

year  per capita income (US$)
0  1970              3399.299037
1  1971              3768.297935
2  1972              4251.175484
3  1973              4804.463248
4  1974              5576.514583
5  1975              5998.144346
6  1976              7062.131392
7  1977              7100.126170
8  1978              7247.967035
9  1979              7602.912681

In [71]:
year_df = df.drop('per capita income (US$)',axis='columns')
year_df.head(10)

year
0  1970
1  1971
2  1972
3  1973
4  1974
5  1975
6  1976
7  1977
8  1978
9  1979

In [72]:
price = df['per capita income (US$)']
price.head(10)

0    3399.299037
1    3768.297935
2    4251.175484
3    4804.463248
4    5576.514583
5    5998.144346
6    7062.131392
7    7100.126170
8    7247.967035
9    7602.912681
Name: per capita income (US$), dtype: float64

In [73]:
reg=linear_model.LinearRegression()
reg.fit(year_df,price)

LinearRegression()

In [74]:
reg.predict([[2020]])

array([41288.69409442])

In [75]:
reg.coef_

array([828.46507522])

In [76]:
reg.intercept_

-1632210.7578554575

In [77]:
828.46507522*2020-1632210.7578554575

41288.694088942604

In [78]:
# EXERCISE FROM KAGGLE DATASET

In [105]:
new_df = pd.read_csv("C:\\Users\\shiva\\Desktop\\MACHINE LEARNING\\archive\\Salary.csv")
new_df.head(10)

YearsExperience  Salary
0              1.1   39343
1              1.3   46205
2              1.5   37731
3              2.0   43525
4              2.2   39891
5              2.9   56642
6              3.0   60150
7              3.2   54445
8              3.2   64445
9              3.7   57189

In [106]:
ye = new_df.drop('Salary',axis='columns')

In [107]:
salary = new_df.Salary

In [108]:
reg.fit(ye,salary)

LinearRegression()

In [109]:
reg.predict([[14]])

array([151106.70085341])

In [110]:
reg.score(ye,salary)

0.9651633106751443

In [111]:
reg.coef_

array([8731.94104706])

In [112]:
reg.intercept_

28859.52619453144

In [113]:
8731.94104706*14+28859.52619453144

151106.70085337144