In [53]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
from sklearn import linear_model
from word2number import w2n
import math

In [54]:
df = pd.read_csv("E:\\MACHINE LEARNING\\hiring.csv")
df

experience  test_score  interview_score  salary($)
0        NaN         8.0                9      50000
1        NaN         8.0                6      45000
2       five         6.0                7      60000
3        two        10.0               10      65000
4      seven         9.0                6      70000
5      three         7.0               10      62000
6        ten         NaN                7      72000
7     eleven         7.0                8      80000

In [56]:
df.test_score.mean()
mean = math.floor(df.test_score.mean())
mean

7

In [57]:
df.test_score = df.test_score.fillna(mean)
df

experience  test_score  interview_score  salary($)
0        NaN         8.0                9      50000
1        NaN         8.0                6      45000
2       five         6.0                7      60000
3        two        10.0               10      65000
4      seven         9.0                6      70000
5      three         7.0               10      62000
6        ten         7.0                7      72000
7     eleven         7.0                8      80000

In [58]:
df.experience = df.experience.fillna('zero')
df

experience  test_score  interview_score  salary($)
0       zero         8.0                9      50000
1       zero         8.0                6      45000
2       five         6.0                7      60000
3        two        10.0               10      65000
4      seven         9.0                6      70000
5      three         7.0               10      62000
6        ten         7.0                7      72000
7     eleven         7.0                8      80000

In [59]:
df.experience = df.experience.apply(w2n.word_to_num)

In [60]:
df

experience  test_score  interview_score  salary($)
0           0         8.0                9      50000
1           0         8.0                6      45000
2           5         6.0                7      60000
3           2        10.0               10      65000
4           7         9.0                6      70000
5           3         7.0               10      62000
6          10         7.0                7      72000
7          11         7.0                8      80000

In [61]:
new_df = df.drop('salary($)',axis='columns')
new_df

experience  test_score  interview_score
0           0         8.0                9
1           0         8.0                6
2           5         6.0                7
3           2        10.0               10
4           7         9.0                6
5           3         7.0               10
6          10         7.0                7
7          11         7.0                8

In [62]:
salary = df['salary($)']
salary

0    50000
1    45000
2    60000
3    65000
4    70000
5    62000
6    72000
7    80000
Name: salary($), dtype: int64

In [75]:
reg = linear_model.LinearRegression()
reg.fit(new_df,salary)

LinearRegression()

In [77]:
reg.predict([[2,9,6]])

array([53713.86677124])

In [78]:
reg.coef_

array([2922.26901502, 2221.30909959, 2147.48256637])

In [79]:
reg.intercept_

14992.65144669314

In [80]:
2*2922.26901502+9*2221.30909959+6*2147.48256637+14992.65144669314

53713.86677126314

In [81]:
reg.predict([[12,10,10]])

array([93747.79628651])

In [82]:
reg.score(new_df,salary)

0.977013901427314

In [95]:
#EXERCISE FROM KAGGLE DATASET

In [98]:
df2 = pd.read_csv("E:\\MACHINE LEARNING\\Cellphone.csv")
df2

Price  internal mem  ram  battery
0    2357            16    3     2610
1    1749             4    4     1700
2    1916             8    2     2000
3    1315             4    2     1400
4    1749             4    1     1700
5    2137            16    2     2500
6    1238             8    1     1560
7    2137            16    2     2500
8    1315             4    4     1400
9    2580            16    2     2800
10   2438            32    4     4000

In [107]:
reg = linear_model.LinearRegression()
reg.fit(df2[['internal mem','ram','battery']],df2['Price'])

LinearRegression()

In [108]:
reg.predict([[16,4,2610]])

array([2049.27924603])

In [109]:
reg.predict([[4,4,1800]])

array([1924.85955081])

In [110]:
reg.predict([[15,2,2500]])

array([2082.87026771])

In [111]:
reg.score(df2[['internal mem','ram','battery']],df2['Price'])

0.8895060140228976

In [112]:
reg.predict([[32,3,2900]])

array([1019.39678494])